### ISSUE TITLE
No credit to Mastodon developers

### ISSUE THREAD

**Issue by drequivalent** [etherhive/etherhive#6]
Hello. It seems that your social engine is using the code (basically, the entire codebase) from Mastodon.

Now, I'm not here for a "cease and dessist order" or anything. I'm not one of the blockchain-phobic crowd, that fears the word like it's some kind of deadly disease, and not just a tool. If you want to fork Mastodon, I personally am okay with that, it's free software, you can do anything with it. But please at least acknowledge to your users that this is just a fork. Most of this codebase is not written by you. Claiming that you came up with the idea of federated social network, or implemented the protocols is dishonest, and it has to stop.

Again: it should be made clear to all your users that Hiveway is a fork of Mastodon. Otherwise, it's a violation of GNU GPL license.

**Comment by tobypinder** [comment]
#4 and #5 appear to address the immediate legal issues, but additionally it would be wise for the reputation of the Hiveway community (and coin offering) that it were transparent about it's software stack for the sake of potential investor clarity.

It is additionally worth pointing out that Mastodon is AGPL not GPL, a minor but important distinction.

**Comment by ghost** [comment]
@tobypinder Blablabla, just add a fucking copyright notice to the footer stating, that it's just a lame ripoff and we're fine. I'm not your mommy, but it has to be. Even my work is sticking in it and I'm not okay with it seeing such a poorly made ripoff.

**Comment by ghost** [comment]
And one thing left: Greetings to John McAffee, this fucking scum

**Comment by hiveway** [comment]
Added the following line to the README.md:

Hiveway is a derived work from Mastodon (https://github.com/tootsuite/mastodon),

**Comment by drequivalent** [comment]
@tobypinder Thank you for correction on licenses.
Actually, yes, you're right. I do, from time to time, invest in and/or donate to various privacy/decentralization projects. If I were to invest in a project like this, and then found out that the code wasn't original, but I **was not told about it upfront by the project**, I'd really think twice or thrice about sending my money this way and investing in your endeavor.

Like, most cryptocurrencies are pretty transparent about where their code came from (like, Litecoin says upfront on its splash screen that it's a Bitcoin fork, etc.) Why should that be any different here?

**Comment by fluffy-critter** [comment]
Even with the update to the README this is still in violation of the AGPL, as it is itself not AGPL-licensed.
